// Module included in the following assemblies:
//
// * about-ocp-monitoring/about-ocp-monitoring.adoc

:_mod-docs-content-type: CONCEPT
[id="monitoring-stack-overview_{context}"]
= {product-title} overview

[role="_abstract"]
{ocp} includes a preconfigured, preinstalled, and self-updating monitoring stack that monitors core platform components. You also have the option to enable _user workload monitoring_ to monitor your own projects.

Core platform monitoring::
A cluster administrator can configure the monitoring stack with the supported configurations. {ocp} delivers monitoring best practices out of the box.
+
_A set of alerts_ is included by default that notify administrators about issues with a cluster. _Default dashboards_ in the {ocp} web console include visual representations of _cluster metrics_ to help you quickly understand the state of your cluster. With the {ocp} web console, you can access metrics and manage alerts.

User workload monitoring::
After installing {ocp}, cluster administrators can optionally enable user workload monitoring. By using this feature, cluster administrators, developers, and other users can configure how services and pods are monitored in their own projects.

As a cluster administrator, you can find answers to common problems, such as user metrics unavailability and high consumption of disk space by Prometheus, in "Troubleshooting monitoring issues".

[NOTE]
====
In {product-dedicated} and {product-rosa}, when you install your cluster, user workload monitoring is enabled by default. 

With user workload monitoring enabled, you can monitor your own projects in isolation from Red{nbsp}Hat Site Reliability Engineering (SRE) platform metrics. You can monitor your own projects without the need for an additional monitoring solution.

The `dedicated-admin` user has default permissions to configure and access monitoring for user-defined projects.

Optionally, you can disable monitoring for user-defined projects during or after a cluster installation.
====
