// Module included in the following assemblies:
//
// * observability/monitoring/enabling-alert-routing-for-user-defined-projects.adoc

:_mod-docs-content-type: CONCEPT
[id="enabling-alert-routing-for-user-defined-projects_{context}"]
= Enabling alert routing for user-defined projects

[role="_abstract"]
An administrator can enable alert routing for user-defined projects.
This process consists of the following steps:

* Enable alert routing for user-defined projects:
** Use the default platform Alertmanager instance.
** Use a separate Alertmanager instance only for user-defined projects.
+
[IMPORTANT]
====
In {product-rosa} and {product-dedicated}, the `dedicated-admin` user can enable alert routing for user-defined projects only by using a separate Alertmanager instance for user-defined projects.
====
* Grant users permission to configure alert routing for user-defined projects.

After you complete these steps, developers and other users can configure custom alerts and alert routing for their user-defined projects.